<?php
/**
*
* @package Icy Phoenix
* @version $Id$
* @copyright (c) 2008 Icy Phoenix
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/**
*
* @Icy Phoenix is based on phpBB
* @copyright (c) 2008 phpBB Group
*
*/

/**
*
* @Extra credits for this file
* Lopalong
*** French Translation Vendethiel and Yros **
*/

if (!defined('IN_ICYPHOENIX'))
{
	exit;
}

//
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--", "Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
// The FAQ items will appear on the FAQ page in the same order they are listed in this file


$faq[] = array("--", "Probl&egrave;mes avec l'inscription et la connexion");
$faq[] = array("Pourquoi ne puis-je pas me connecter ?", "Vous &ecirc;tes-vous enregistr&eacute; ? S&eacute;rieusement, vous devez &ecirc;tre enregistr&eacute; pour vous connecter. Peut-&ecirc;tre avez-vous &eacute;t&eacute; banni du Froum ? (Un message sera affich&eacute; si c'est le cas). Si c'est le cas, contactez un administrateur pour savoir pourquoi. Si vous &ecirc;tes enregistr&eacute; et n'&ecirc;tes pas banni, re-v&eacute;rifiez votre nom d'utilisateur. Le probl&egrave;me viens souvent de la. Si le probl&egrave;me n&#39;est toujours pas regl&eacute;, contactez un administrateur - La configuration a pu &ecirc;tre mal faite.");
$faq[] = array("Pourquoi dois-je obligatoirement &ecirc;tre inscrit ?", "Vous n'&ecirc;tes pas oblig&eacute; - C'est juste n&eacute;c&eacute;ssaire pour envoyer des messages et voir certains forums. De plus, &ecirc;tre inscrit vous permettrait d'acc&eacute;der a &eacute;normement de fonctionnalit&eacute;s innovantes, inutilisable pour un invit&eacute, comme par exemple la messagerie, les groupes, les avatars, et&ccedil;. S'inscrire est vraiment rapide et pratique !");
$faq[] = array("Pourquoi suis-je automatiquement d&eacute;connect&eacute; ?", "Si vous ne cochez pas la case <i>Connexion automatique</i>, le forum ne vous reconnectera pas &agrave; votre prochaine visite. Cela permet d'&eacute;viter que d'autres personnes utilisent votre compte si vous &ecirc;tes plusieurs &agrave; utiliser cet ordinateur. <b>NE COCHEZ JAMAIS CETTE CASE DEPUIS UN LIEU PUBLIC !</b> (universit&eacute;, cybercaf&eacute;, librairie, et&ccedil; ...).");
$faq[] = array("Comment puis-je faire pour faire dispara&icirc;tre mon nom de la liste des utilisateurs ?", "
Dans votre profil, vous avez une option <i>Cacher mon status en ligne</i>, si vous passez cette option sur <i>Oui</i> les seuls &agrave; vous voir dans la liste des personnes connect&eacute;s seront vous et l'&Eacute;quipe du site (Mod&eacute;rateurs, Administrateurs, ...). Vous serez alors compt&eacute; comme un utilisateur cach&eacute;/masqu&eacute;.");
$faq[] = array("J'ai perdu mon mot de passe !", "Pas de panique ! M&ecirc;me si vous ne pouvez pas le r&eacute;cup&eacute;rer, vous pouvez en cr&eacute;er un nouveau. Pour cela, allez sur la page de connexion et cliquez sur <u>J'ai oubli&eacute; mon mot de passe</u>. Suivez les instructions et vous pourrez vous reconnecter en un rien de temps !.");
$faq[] = array("Je me suis enregistr&eacute; mais je ne peux pas me connecter !", "Premi&egrave;rement, v&eacute;rifiez que vous avez entr&eacute; la bonne combinaison nom d&#39;utilisateur / mot de passe. Si ils sont bons, deux choses se sont peut-&ecirc;tre pass&eacute;e: Si la COPPA est activ&eacute;e et que vous avez cliqu&eacute; sur <u>J'ai moins de 13 ans</u> pendant que vous vous enregistriez, vous devez suivre les instructions que vous avez re&ccedil;u par e-mail. Si ce n'est pas le cas, il est possible que votre compte ait besoin d'&ecirc;tre activ&eacute;. L'activation se fait: sous par vous-m&ecirc;me, vous devriez alors avoir re&ccedil;u un e-mail, sois par l'aministrateur, et dans ce cas vous devrez attendre. Si vous n'avez pas re&ccedil;u d'e-mail, v&eacute;rifiez que votre adresse e-mail est valide. Si c'est le cas, attendez ou contactez l'administrateur du forum.");
$faq[] = array("Je m'&eacute;tais enregistr&eacute; mais je ne peux plus me connecter !", "Premi&egrave;rement, v&eacute;rifiez que vous avez entr&eacute; la bonne combinaison nom d&#39;utilisateur / mot de passe. Si vous ne vous &ecirc;tiez jamais connect&eacute; ou que vous n'aviez post&eacute; aucun message, il est possible que les administrateurs aient supprim&eacute; votre compte, pour r&eacute;duire la taille des utilisateurs dans la base de donn&eacute;es. Essayer de vous inscrire, si vous recevez une erreur &quot;nom d'utilisateur utilis&eacute;&quot;, c'est que votre mot de passe est mauvais.");


$faq[] = array("--", "Pr&eacute;f&eacute;rences utilisateurs et options");
$faq[] = array("Comment puis-je modifier mes pr&eacute;f&eacute;rences ?", "Toutes les options (si vous &ecirc;tes enregistr&eacute;) sont enregistr&eacute;es dans la base de donn&eacute;es. Pour les modifier, cliquez sur le lien <u>Profil</u>.");
$faq[] = array("L'heure n'est pas correcte !", "Il est possible que le serveur soit dans un fuseau horaire diff&eacute;rent du votre. Si c'est le cas, vous pouvez modifier le Fuseau Horaire depuis votre profil, pour l'accorder a votre viille, par exemple Londre, Paris, New York, Sydney, et&ccedil;. Vous ne pouvez modifier cette option que si vous &ecirc;tes enregistr&eacute;, alors si vous ne l'&ecirc;tes pas, c'est le bon moment pour le faire !");
$faq[] = array("J'ai chang&eacute; mon fuseau horaire et l'heure est toujours mauvaise !", "Si vous &ecirc;tes certain d'avoir correctement modifi&eacute; le fuseau horaire, la cause la plus probable est le fait que l'heure d'&eacute;t&eacute; sois/ne sois pas activ&eacute;. Cela peut aussi se changer dans votre profil.");
$faq[] = array("Ma langue n'est pas dans la liste !", "La plus probable des raisons est qu'aucune traduction n'ait &eacute;t&eacute; faite, ou que l'administrateur n'ait pas install&eacute; le pack. Dans le second cas, contactez l'administrateur, sinon ... Vous pouvez bien s&ucirc;r traduire vous-m&ecirc;me ! Sachez toutefois que traduire IcyPhoenix peut &ecirc;tre tr&egrave;s long, toutefois la communaut&eacute; vous remerciera &eacute;normement ! Des compl&eacute;ments d'information peuvent &ecirc;tre trouv&eacute; sur la page officiel d'IcyPhoenix (voir le lien en fin de page).");
$faq[] = array("Comment puis-je afficher une image sous mon pseudo, dans mes messages ?", "Il y a deux types diff&eacute;rents d'images sous les pseudos: Le premier est un rang, associ&eacute; selon votre r&ocirc;le dans le site ou votre anciennet&eacute/votre date d'inscription/le fait que vous soyez bannis. Vous ne pouvez choisir votre rang. En dessous des rangs apparait l'avatar, qui est g&eacute;n&eacute;ralement une image unique. Si l'administrateur autorise les membres &agrave; avoir des avatars, vous pouvez le changer dans votre Profil. S'ils ne sont pas activ&eacute;s, vous pouvez toujours demander une raison aux administrateurs");
#$faq[] = array("Comment pui?", "In general you cannot directly change the wording of any rank (ranks appear below your username in topics and on your profile depending on the style used). Most boards use ranks to indicate the number of posts you have made and to identify certain users. For example, moderators and administrators may have a special rank. Please do not abuse the board by posting unnecessarily just to increase your rank -- you will probably find the moderator or administrator will simply lower your post count."); //J'ai dit au dessus que ce n'etait pas possible ou alors avec certaines conditions.
$faq[] = array("Quand j'essaye d'envoyer un e-mail a un utilisateur, je suis oblig&eacute; de me connecter.", "D&eacute;sol&eacute;, mais seuls les utilisateurs enregistr&eacute;s peuvent envoyer des e-mails via le formulaire (si l'administrateur a activ&eacute; la fonction). Cela permet d'&eacute;viter que n'importe qui puisse envoyer anonymement des e-mails a une personne.");

$faq[] = array("--", "Probl&egrave;s avec les messages");
$faq[] = array("Comment puis-je cr&eacute;er un sujet dans un forum ?", "C'est facile, vous avez juste a cliquer sur le bouton &quot;Nouveau sujet&quot (ou &quot;New Topic&quot;). Vous serez peut-&ecirc;tre oblig&eacute; de vous inscrire pour envoyer un message (En bas du forum, un indicateur est pr&eacute;sent, <i>Vous <b>pouvez</b> cr&eacute;er de nouveaux</i> sujets, sondages, et&ccedil;).");
$faq[] = array("Comment puis-je supprimer un message ?", "Sauf si vous &ecirc;tes un administateur / un mod&eacute;rateur, vous pouvez uniquement supprimer vos propres messages. Vous pouvez &eacute;diter un message (souvent, il existe une limite de temps) en cliquant sur le bouton <i>&Eacute;diter</i>. Si quelqu'un a r&eaucte;pondu au sujet apr&egrave;s votre &eacute;dition, un petit cadre permettra de faire un suivi des &eacute;ditions de votre message.  Cela n'apparait pas quand un mod&eacute;rateur / administrateur &eacute;ditent un message (sauf si ceux-ci d&eacute;cident de laisser une raison). Veuillez aussi noter que les utilisateurs normaux ne peuvent supprimer de message une fois que quelqu'un a r&eacute;pondu au sujet.");
$faq[] = array("Comment puis-je ajouter une signature &agrave; mes messages ?", "Vous pouvez modifier votre signature dans votre profil. Une fois ceci fait, cochez la case '<i>Ajouter la signature</i>' en bas du formulaire d'envoi de message. Vous pouvez aussi activer votre signature par d&eacute;faut (via le profil ici). Vous pourrez toujours enlever votre signature pour certaines exceptions en d&eacute;cochant la page sur le formulaire d'envoi.");
$faq[] = array("Comment puis-je cr&eacute;er un sondage ?", "Cr&eacute;er est sondage est tr&egrave;s facile. Lorsue vous vous cr&eacute;ez un sujet (ou que vous &eacute;ditez le premier message d'un sujet, si vous en avez la permission), vous devriez un formulaire <i>Ajouter un sondage</i>. Si vous ne voyez pas ce formulaire, c'est problablement que vous n'avez pas la permission requise. Vous devez entrer un titre et proposer au moins 2 options (pour en ajouter, cliquez sur le bouton <i>Ajouter une option</i>. Vous pouvez aussi mettre une limite de temps, 0 &eacute;tant &quot;pas de limitation&quot;. Il y a un nombre maximum d'options, choisis par les administrateurs.");
$faq[] = array("Comment puis-je &eacute;ditere ou supprimer un sondage ?", "Comme pour les messages, les sondages ne peuvent &ecirc;tre supprim&eacute;s que par leur cr&eacute;reur, les mod&eacute;rateurs ou les administrateurs. Pour &eacute;diter un sondage, &Eacute;ditez le premier message du sujet, si personne n'a vot&eacute;, vous pourrez modifier ou supprimer le sondage, sinon, seuls les mod&eacute;rateurs et les administrateurs pourront (afin de ne pas permettre des trucages, exemple: je cr&eacute;e un sondage avec comme option a et b. Au bout de 20 jours, j'ai 15 en a et 25 en b. Je veux que a gagne, je supprime b et le remet, b est alors a 0 !)");
$faq[] = array("Pourquoi ne puis-je acc&eacute;der a certains forums ?", "Certains forums sont limit&eacute;s a certains utilisateurs / groupes. Pour pouvoir voir le forum / lire les messages / en ajouter / et&ccedil;, vous aurez besoin d'une autorisation sp&eacute;ciale que seuls les mod&eacute;rateurs du forum et les administrateurs sont capable de vous donnez.");
$faq[] = array("Pourquoi ne puis-je pas voter dans les sondages ?", "Seuls les utilisateurs enregistr&eacute;s peuvent voter, pour emp&ecirc;cher le d&eacute;s&eacute;quilibrage par robots. Si vous &ecirc;tes inscrit mais ne pouvez toujours pas voter, c'est s&ucirc;rement parce que vous n'avez pas l'autorisation requise.");

$faq[] = array("--", "Formattage et type de sujets");
$faq[] = array("Qu'est-ce que le BBCode ?", "Le BBCode est un pseudo-langage pour remplacer le HTML. Le BBCode peut &ecirc;tre activ&eacute; ou d&eacute;sactiv&eacute; par l'adminisrateur. Vous pouvez aussi le d&eacute;sactiver dans vos messages en d&eacute;cochant <i>Activer le BBCode</i> dans le formulaire d'envoi de message. Le BBCode a le m&ecirc;me style que le HTML: [ et ] a la place de &lt; et &gt; mais le BBCode offre plus de contr&ocirc;le sur l'affichage. Pour plus d'information sur les BBCodes, regardez le guide (accessible via le formulaire d'envoi de message, ou ce lien: <a href=\"faq.php?mode=bbcode\">Aide BBCode</a>).");
$faq[] = array("Puis-je utiliser le HTML ?", "Cela d&eacute;pend totalement des choix des administrateurs. Attention toutefois, seules certaines balises fonctionneront. Ceci est une <i>mesure de s&eacute;curit&eacute;</i> pour &eacute;viter les injections de code ou emp&ecirc;cher le th&egrave;me d'&ecirc;tre affich&eacute;. Si le HTML est activ&eacute; vous pouvez le d&eacute;sactiver sur un message en d&eacute;cochant la case dans le formulaire d'envoi de message.");
$faq[] = array("Que sont les smileys ?", "Les smileys, ou les &eacute;motic&ocirc;nes, sont des petits personnages qui expriment des sentiments avec un code simple, comme par exemple :) (heureux) ou :( (malheureux). La liste totale des &eacute;motic&ocirc;nes peut &ecirc;tre vue dans le formulaire d'envoi de message. &Eacute;vitez d'en abuser, ils peuvent rendre les messages illisibles et un mod&eacute;rateur pourrait d&eacute;cider de les retirer voir de supprimer le message.");
$faq[] = array("Puis-je envoyer des images ?", "Vous pouvez &eacute;videmment ajouter des images dans vos messages. Il est possible que les administrateurs aient activ&eacute;s des fonctions qui vous permettront d'envoyer directement sur le site et cela de 3 fa&ccedi;: En joignant le fichier, en ajoutant l'image dans l'album ou en envoyant l'image. L'Album est la meilleure solution si vous voulez aussi rendre la photo disponible dans la galerie, et vous aurez un meilleur contr&ocirc;le sur la mani&egrave;re dont sont g&eacute;ner&eacute;s les miniatures. La jointure de fichier et l'envoi d'images peuvent directement &ecirc;tre fait sur la page d'envoi de message. Envoyer une image au lieu de l'&quot;attacher&quot; est une bonne id&eacute;e si vou voulez controller la position de l'image ... Si les administrateurs ont d&eacute;sactiv&eacute;s la possibilit&eacute; d'envoyer directement l'image sur le serveur, vous devriez voir un lien pour envoyer vos images. Vous ne pouvez envoyer des images stock&eacute;es sur votre propre PC (sauf si votre PC est un serveur public) ni envoyer des messages sur des syst&egrave;mes avec connexions comme Hotmail / Yahoo ou n'importe quel site prot&eacute;g&eacute; par un mot de passe. Pour afficher l'image vous pouvez utiliser le BBCode [img] ou la balise HTML &lt;img /&gt; (si celle-ci est autoris&eacute;e).");
$faq[] = array("Que sont les annonces ?", "Les annonces contiennent toujours d'importantes informations et vous devriez les liers d&egrave;s que vous pouvez. Les annonces apparaissent en haut de chaque forum o&ugrave; elles ont &eacute;t&eacute; post&eacute;es. Pour poster des annonces vous aurez besoin d'une permission sp&eacute;ciale (que seuls les administrateurs peuvent donner). Les annonces globales sont des annonces sp&eacute;ciales qui sont montr&eacute;es dans tous les forums, et pas uniquement dans celui dans lequel elles sont post&eacute;es.");
$faq[] = array("Que sont les Post-It ?", "Les Post-It apparaissent sous les annonces dans la vue d'un forum et uniquement sur la premi&egrave;re page. Ces sujets sont souvent importants et vous feriez mieux de les lire. Comme pour les annonces, il faut une autorisation sp&eacute;ciale pour envoyer des Post-It.");
$faq[] = array("Que sont les sujets verrouill&eacute;s ?", "Le verrouillage des sujets est un moyen qui permet aux mod&eacute;rateurs / administrateurs de r&eacute;guler le forum. En effet, vous ne pouvez ni r&eacute;pondre ni voter dans les sujets verrouill&eacute;s. Les sujets peuvent verrouill&eacute;s pour &eacute;norm&eacute;ment de raisons.");

$faq[] = array("--", "Niveaux d'utilisateurs et groupes");
$faq[] = array("Qui sont les administrateurs ?", "Les administrateurs sont ceux qui ont le plus haut niveau sur le forum, ayant un contr&ocirc;le total sur celui-ci. Ils g&egrave;rent les op&eacute;rations sur le forum comme les permissions, les bannissements, les groupes ... Ils ont aussi les pouvoirs de mod&eacute;rateurs sur tous lse forums.");
$faq[] = array("Qui sont les mod&eacute;rateurs ?", "Les mod&eacute;rateurs sont des personnes qui r&eacute;gulent le forum. Ils peuvent &eacute;diter ou supprimer des messages ainsi que verrouiller, d&eacute;verrouiller, d&eacute;placer, supprimer, joindre ou d&eacute;couper les sujets dans le forum qu'ils mod&eacute;rent.");
$faq[] = array("Que sont les groupes d'utilisateurs ?", "Les groupes d'utilisateurs sont un moyen pour les administrateurs pour grouper les utilisateurs. Chaque utilisateur peut avoir plusieurs groupes et chaque groupe peut avoir plusieurs utilisateurs. Chaque groupe peut avoir des droits sp&eacute;ciaux, ce qui permet aux administrateurs de faciliter l'ajout de mod&eacute;rateur ou de donner l'acc&egrave;s a un forum priv&eacute;, et&ccedil;.");
$faq[] = array("Comment puis-je rejoindre un groupe ?", "Pour rejoindre un groupe cliquez sur le lien dans la liste des liens, vous pourrez alors voir tous les groupes. Tous les groupes ne sont pas <i>ouverts</i> - certains sont &quot;cach&eacute;s&quot; et vous ne pourrez pas savoir qui appartient a ce groupe. Si le groupe est ouvert vous verrez apparaitre un groupe en cliquant sur le bouton appropri&eacute;. Le mod&eacute;rateur du groupe devra alors accepter votre requ&ecirc;te - il est probable que ledit mod&eacute;rateur vous demande vos motivatiions. Veuillez ne pas harceler les mod&eacute;rateurs ayant refus&eacute; votre requ&ecirc;te - ils ont leurs propres raisons.");
$faq[] = array("Comment puis-je devenir mod&eacute;rateur d'un groupe ?", "Les groupes &eacute;tants cr&eacute;&eacute;s par les administrateurs, les mod&eacute;rateurs de groupes le sont aussi. si vous voulez cr&eacute;er un groupe, contactez un administrateur pour lui faire votre proposition.");

$faq[] = array("--", "Messages priv&eacute;s");
$faq[] = array("Je ne peux pas envoyer de messages priv&eacute;s !", "Il y a trois raisons possibles: Vous n'&ecirc;tes pas enregistr&eacute;/connect&eacute;, les administrateurs ont d&eacute;sactiv&eacute; les messages priv&eacute;s ou ils vous ont (vous) emp&ecirc;ch&eacute; d'en envoyer. Dans le dernier cas, contactez un administrateur pour leur demander pourquoi.");
$faq[] = array("Je re&ccedil;ois des messages priv&eacute;s non voulus !", "Dans le futur il y aura un syst&egrave;me d'utilisateurs ignor&eacute;s. Pour l'instant, contactez un des administrateurs du forum avec des preuves - ils peuvent emp&ecirc;cher des personnes d'envoyer des messages priv&eacute;s.");
$faq[] = array("J'ai re&ccedil;u un e-mail abusif / de spam !", "Nous sommse d&eacute;sol&eacute; de savoir &ccedil;. Toutefois, le formulaire d'envoi d'e-mail garde une trace des messages envoy&eacute;s. Contactez un administrateur avec une copie de l'e-mail. Ils pourront alors prendre les mesures n&eacute;c&eacute;ssaires pour que l'utilisateur sois sanctionn&eacute;.");

$faq[] = array("--", "G&eacute;n&eacute;rateur d'avatar");
$faq[] = array("Qu'est-ce ?", "Le <strong>G&eacute;n&eacute;rateur d'avatar</strong> est utilis&eacute; pour g&eacute;n&eacuute;rer des avatars pour les utilisateurs en voulant.");
$faq[] = array("O&ugrave; puis-je le trouver ?", "Vous devez vous connecter pour l'utiliser. Il se trouve dans votre profil, section <i>Avatar</i>.");
$faq[] = array("Comment puis-je sauvegarder l'avatar ?", "Normalement un lien devrait &ecirc;tre pr&eacute;sent, disant <strong>Cliquez ici pour utiliser cet avatar</strong>.");

$faq[] = array("--", "Album Photo");
$faq[] = array("Comment puis-je acc&eacute;der a l'Album Photo ?", "Utilisez le lien &quot;Album Photo&quot; dans les liens de navigation. Cela vous am&egrave;nera dans le dossier principal de l'Album Photo o&ugrave; toutes les photos sont affich&eacute;es. .");
$faq[] = array("Comment puis-je envoyer une image dans l'Album ?", "Une fois que vous &ecirc;tes dans l'Album, s&eacute;lectionnez une cat&eacute;gorie publique ou votre galerie personnelle. Vous devrez alors voir un lien pour envoyer une image, en haut et en bas de la page. Cliquez sur le bouton et suivez les instructions.");
$faq[] = array("Quels sont les dimensions / le poids maximum pour une image et quel doit &ecirc;tre son format ?", "Ces limitations apparaissent sur la page d'envoi d'image. L'administrateur peut les modifier a tout moment.");
#$faq[] = array("What format does my picture have to be in?", "These settings appear on the 'Upload Pic' page. The board administrator sets an upper limit for filesize, defined file extensions and other things for uploaded pictures in the Albums.");
$faq[] = array("Je ne peux toujours pas envoy&eacute; d'image, j'ai un message d'erreur !", "Revenez sur la page d'envoi et v&eacute;rifiez que vous suivez bien toutes les instructions. V&eacute;rifiez que l'image a les bonnes dimensions, ne d&eacute;passe pas le poids maximum, que son type est correct et que vous avez bien remplis les champs n&eacute;c&eacute;ssaires.");
$faq[] = array("J'ai fait une erreur dans le titre/la descritpion de mon image / J'ai d&eacute;cider de retirer cette image. Que puis-je faire ?", "Quand vous regardez un album, il y a plusieurs options. Si les administrateurs l'ont autoris&eacute;, vous devriez trouver un lien &quot;&Eacute;diter&quot; et &quot;Supprimer&quot; qui vous permettra de modifier / supprimer les images.");
#$faq[] = array("How do I delete a pic?", "When viewing an Album, there are several options available to users. If the board administrator has allowed it, you will find the link 'Delete' below each thumbnail which will allow you to remove any picture of your own.");
$faq[] = array("Je voudrais faire savoir a quelqu'un comme j'aime/je n'aime pas une de ses images. Comment puis-je faire ?", "Lors de la vue d'un album, il y a plusieurs options disponbiles. Si les administrateurs l'ont autoris&eacute;, vous devriez trouver les liens &quot;Noter&quot; et &quot;Commenter&quot; en dessous de chaque image.");

$faq[] = array("--", "Fichiers joints");
$faq[] = array("Comment puis-je joindre un/des fichier(s) ?", "Sur le formulaire d'envoi de message (et si vous en avez l'autorisation), vous devriez voir un cadre <i>Joindre un fichier</i>. Choississez le fichier &agrave; envoyer, et ajoutez le fichier.<br />Attention toutefois, le nombre de fichier joignables dans un message et le nombre de fichier joignables au total sont limit&eacute;s");
$faq[] = array("Comment puis-je joindre un fichier apr&egrave;s avoir envoy&eacute; le message ?", "Pour joindre un/des nouveau(x) fichier(s), vous n'avez qu'a suivre les instructions ci-dessous sur le formulaire d'&eacute;dition du message.");
$faq[] = array("Comment puis-je supprimer un fichier joint ?", "Lorsque vous &eacute;ditez votre message, cliquez sur le lien <i>Supprimer le fichier joint</i> dans la liste des fichiers joints.");
$faq[] = array("Comment puis-je mettre &agrave; jour le commentaire d'un fichier ?", "&Eacute;ditez votre message, modifier le commentaire pour le fichier et cliquez sur le bouton <i>Mettre &agrave; jour le commentaire</i> dans la liste des fichiers joints.");
$faq[] = array("Pourquoi les fichiers joints ne sont pas visibles sur le message ?", "Il est possible que l'extension ne plus autoris&eacute;e, ou plus probablement qu'un mod&eacute;rateur/administrateur l'ait supprim&eacute;.");
$faq[] = array("Pourquoi ne puis-je pas joindre de fichier ?", "Pour joindre un fichier, il faut une permission sp&eacute;ciale, qui est accord&eacute;e par d&eacute;faut, toutefois les administrateurs ont peut-&ecirc;tre d&eacute;cid&eacute; de ne pas accorder ce droit dans ce forum.");
$faq[] = array("J'ai les permissions n&eacute;c&eacute;ssaires, pourquoi ne puis-je pas joindre de fichier ?", "Il est possible que vous ayez atteint votre liimite, que les administrateurs aient retir&eacute;s votre permission ou que votre fichier soit trop lourd / d'un type interdit. Vous devriez comprendre avec le message d'erreur.");
$faq[] = array("Pourquoi ne puis-je pas supprimer / voir / t&eacute;l&eacute;charger de fichiers joints ?", "Dans certains forums, une permission sp&eacute;ciale est n&eacute;c&eacute;ssaire pour supprimer / voir / t&eacute;l&eacute;charger les fichiers joints. Si vous voulez avoir la permission, tentez de contacter un administrateur.");
#$faq[] = array("Pourquoi ne puis-je pas voir / t&eacute;l&eacute;charger les fichiers joints ?", "Dans certains On some viewing/downloading forums attachments may be limited to certain users or groups. To view/download attachments you may need special authorization, only the forum moderator and board admin can grant this access, you should contact them.");
$faq[] = array("Qui puis-je contacter si je trouve un t&eacute;l&eacute;chargement abusif ?", "Vous pouvez alertir les mod&eacute;rateurs en cliquant sur le carton bleu, a c&ocirc;t&eacute; du titre du message.");

$faq[] = array("--", "T&eacute;l&eacute;chargements");
$faq[] = array("O&ugrave; puis-je trouver les t&eacute;l&eacute;chargements ?", "Le lien est situ&eacute; dans la barre de navigation, voici un lien direct: [<a href=\"downloads.php\">T&eacute;l&eacute;chargements</a>]");
$faq[] = array("Que signifie <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" />?", "T&eacute;l&eacute;chargement impossible. Il est possible que la limite de t&eacute;l&eacute;chargement soit atteinte pour ce mois-ci.");
$faq[] = array("Que signifie <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />?", "T&eacute;l&eacute;chargement impossible. Cela peut &ecirc;tre:<br />- Le t&eacute;l&eacute;chargement a &eacute;t&eacute; bloqu&eacute; par un administrateur.<br />- Il faut &ecirc;tre connect&eacute; pour t&eacute;l&eacute;charger.<br />- Vous n'avez pas suffisament de trafic.<br />- Une limite de messages existe et vous n'en avez pas assez.");
$faq[] = array("Que signifie <img border=\"0\" src=\"" . $images['Dl_grey'] . "\" alt=\"\" title=\"\" />?", "T&eacute;l&eacute;chargement externe: le fichier n'est pas situ&eacute; sur le serveur. &Eacute;quivalent &agrave; <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />, sauf que le traffic de l'utilisateur / le traffic global ne diminueront pas.");
$faq[] = array("Que signifie <img border=\"0\" src=\"" . $images['Dl_white'] . "\" alt=\"\" title=\"\" />?", "Comme <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />, le traffic de l'utilisateur ne sera pas diminu&eacute;. Seuls les utilisateurs enregistr&eacute;s peuvent t&eacute;l&eacute;charger ce fichier librement. Le traffic global diminuera.");
$faq[] = array("Que signifie <img border=\"0\" src=\"" . $images['Dl_yellow'] . "\" alt=\"\" title=\"\" />?", "Le t&eacute;l&eacute;chargement est possible sous certaines conditions. Vous devez &ecirc;tre connect&eacute;. Votre traffic et le traffic global diminueront.");
$faq[] = array("Que signifie <img border=\"0\" src=\"" . $images['Dl_green'] . "\" alt=\"\" title=\"\" />?", "T&eacute;l&eacute;chargement libre. Ce fichier peut aussi &ecirc;tre t&eacute;l&eacute;charg&eacute; par les invit&eacute;s. Le traffic global diminuera.");
$faq[] = array("Pourquoi ne puis-je t&eacute;l&eacute;charger aucun fichier ?", "Il y a plusieurs raisons possibles. Regardez &agrave; <img border=\"0\" src=\"" . $images['Dl_blue'] . "\" alt=\"\" title=\"\" /> et <img border=\"0\" src=\"" . $images['Dl_red'] . "\" alt=\"\" title=\"\" />.");
$faq[] = array("Quand et comment puis-je renouveller mon traffic ?", "Chaque premier du mois (un mois apr&egrave;s l'inscription, 2, 3 ...), le traffic sera remis a son maximum. Vous pouvez demander aux administrateurs combien est le maximum.");
$faq[] = array("Je voudrais encore t&eacute;l&eacute;charger un fichier, mais je n'ai plus de traffic ?", "Seuls les administrateurs ont le pouvoir de redonner du traffic, essayez de les contacteer. S'ils refusent, attendez le mois prochan.");
$faq[] = array("Comment puis-je noter les t&eacute;l&eacute;chargements ?", "Sous chaque t&eacute;l&eacute;chargement vous trouverez une section pour noter.<br />En cliquant sur &quot;Noter&quot;, un utilisateur peut noter le fichier de 1 (horrible) &agrave; 10 (excellent) points. Vous ne pouvez attribuer qu'une note par t&eacute;l&eacute;chargement.");

$faq[] = array("--", "Lettre d'information");
$faq[] = array("Que sont les lettres d'information ?", "Les lettres d'information sont des e-mails envoy&eacute;s p&eacute;riodiquemment contenant les informations sur les nouveaux messages du forum. Les dur&eacute;e possible sont: une semaine / un jour.");
$faq[] = array("Pourquoi voudrais-je recevoir les lettres d'information ?", "Cela rendra votre vie plus facile. Vous n'aurez plus besoin de visiter ce site directement. Vous n'aurez qu'a lire les lettres d'information et si un sujet vous int&eacute;resse, vous n'aurez qu'a cliquer sur le lien pour voir le sujet. Vous pouvez aussi vous d&eacute;sinscrire a n'importe quel moment.");
#$faq[] = array("How often are digests sent?", "They can be sent daily or weekly. Weekly digests are sent on Sundays.");
$faq[] = array("Quand les lettres d'information sont-elles envoy&eacute;es ?", "Vous pouvez choisir l'heure que vous voulez. Vous recevrez toujours les derni&egrave;res nouvelles donc choissisez une heure qui correspond a votre rythme de vie.");
$faq[] = array("Combien de temps les lettres d'information couvrent-elles ?", "Entre 24h et 7jours, selon que vous ayez choisis journali&egrave;rement / chaque semaine. Les messages plus anciens ne seront pas envoy&eacute;s. Vous pouvez aussi filtrer vos propres messages.");
$faq[] = array("Puis-je faire des s&eacute;lection si je ne veux pas un sommaire coomplet ?", "Oui. Vous pouvez choisir quel(s) forum(s) vous int&eacute;ressent. Par d&eacute;faut, tous les forums auxquels vous avez acc&egrave;s seront s&eacute;lectionn&eacute;s.");
$faq[] = array("Quels sont les formats disponibles ?", "Nous pouvons vous envoyer les lettres d'information sous forme purement textuelle ou HTML. Sauf si votre gestionnaire de mails ne g&egrave;re pas le HTML (tr&egrave;s rare de nos jours), nous vous conseillons le format HTML. Les lettres d'information en texte-seul sont difficiles a lire.");
$faq[] = array("Recevrais-je les messages en entier dans les lettres d'information ?", "Par d&eacute;faut, seuls les 150 premiers caract&egrave;res sont envoy&eacute;s. Vous pouvez aussi choisir de ne voir que le titre. Vous pouvez voir le message avec 50, 100, 150, 300 ou 600 des premiers caract&egrave;res, voir voir tout le message (maximum 32 000 caract&egrave;res). Nous vous recommandons de garder la taille par d&eacute;faut, afin d'&eacute;viter de recevoir de si grosse lettres d'information qu'elles seront illislbes et donc inutiles. Il est aussi possible que les grosses lettres d'information soient rejet&eacute;es par votre ISP ou que votre limite d'espace sois d&eacute;pass&eacute;e.");
$faq[] = array("Comment puis-je m'abonner ?", "Vous n'avez qu'a cliquer sur le lien dans la liste des liens ou cliquez directement ici: <a href=\"./digests.php\">Lettre d'information</a>.");
$faq[] = array("Comment puis-je me d&eacute;sinscrire ?", "Allez sur la page d'inscription et choississez &quot;Aucun&quot; dans le type.");
$faq[] = array("Ma vie priv&eacute;e est-elle prot&eacute;g&eacute;e ?", "Oui, vos lettres d'information ne sont envoy&eacute;es qu'a vous et nous ne communiquons votre adresse a personne. Les autres, selons leurs r&eacute;glages, peuvent avoir des lettres d'information totalement diff&eacute;rentes.");


$faq[] = array("--", "Informations sur les messages non lus dans la base de donn&eacute;es (Unread Posts Informations To DataBase: UPI2DB)");
$faq[] = array("Quelles sont les diff&eacute;rences entre le syst&egrave;me par cookies et UPI2DB ?", "Le syst&egrave;me de cookies est le syst&egrave;me par d&eacute;faut de phpBB2. Quand vous lisez un message, l'information est enregistr&eacute;e dans un cookie sur votre ordinateur comme quoi vous avez lu le sujet. Le probl&egrave;me est que vous perdez les &eacute;tats lu/non lu &agrave; chaque fois que vous fermez votre navigateur. UPI2DB n'enregistre pas les donn&eacute;es sur votre ordinauter, mais dans la base de donn&eacute;es, elles sont donc sauvegard&eacute;es.");
$faq[] = array("Quels sont les avantages et les inconv&eaucute;nients du syst&egrave;me de cookies ?", "<b>Avantages:</b> Le chargement des pages est plus rapide car l'information n'a pas &agrave; &ecirc;tre prise de la base de donn&eacute;es. Les donn&eacute;es sont stock&eacute;es plus longtemps. <b>D&eacute;savantages:</b> &Agrave; chaque fois que vous fermez votre navigateur, tous les messages sont marqu&eacute;s comme &quot;lus&quot;. Un autre d&eacute;savantage est quel les messages &eacute;dit&eacute;s ne seront pas marqu&eacute;s &quot;nouveaux&quot;.");
$faq[] = array("Quels sont les avantages et les inconv&eacute;nients d'UPI2DB ?", "<b>Avantages:</b> Les messages non lus resteront toujours en non lus. Vous n'avez pas a lire tous les nouveaux messages &agrave; chaque fois que vous venez sur le forum. Les messages peuvent aussi &ecirc;tre marqu&eacute;s comme lus pour un temps de " . ( empty( $unread_days ) ? 0 : $unread_days ) . ". Les forums qui ne vous int&eacute;ressent pas peuvent &ecirc;tre marqu&eacute;s &quot;toujours lus&quot; jusqu'a ce que vous modifiez l'otpion. Les messages &eacute;dit&eacute;s seront marqu&eacute;s &quot;&Eacute;dit&eacute;s&quot; et seront s&eacute;par&eacute;s des nouveaux messages. Une fonction de recherche vous permet de voir uniquement les nouveaux messages ou uniquement ceux &eacute;dit&eacute;s. <b>D&eacute;savantages:</b> Cela peut ralentir le chargement de la page. L'&eacute;tat &quot;non lu&quot; d'un message ne sera gard&eacute; que pendant une p&eacute;riode, le message sera apr&egrave;s marqu&eacute; comme automatiquement lu (le maximum par d&eacute;faut est 30 jours).");
$faq[] = array("Ou puis-je faire le changement, je ne vois rien dans mon profil !", "Il est possible que l'administrateur ait d&eacute;sactiv&eacute; le syst&egrave;me UPI2DB, dans ce cas vous serez oblig&eacute; d'utiliser le syst&egrave;me de cookies.");
$faq[] = array("Je ne peux marquer des annonces ou des post-it !", "Il faut absolument lire les annonces et les post-it ! Vous ne pouvez pas les marquer comme lus.");
$faq[] = array("Je dois remarques les sujets en &quot;toujours lus&quot; tous les " . (!empty($config['upi2db_auto_read']) ? $config['upi2db_auto_read'] : 0) . " jours !", "Afin de ne pas rendre le syst&egrave;me trop lourd, la liste des &quot;toujours lus&quot; est r&eacute;guli&egrave;rement vid&eacute;e.");
$faq[] = array("Comment puis-je marquer un forum comme &quot;toujours lu&quot; ?", "Vous n'avez qu'a cliquer sur le bouton &agrave; c&ocirc;t&eacute;e du nom du forum. Une fois cela fait, l'image du forum devrait changer (attention: les annonces eet les Post-It seront marqu&eacute;s comme nouveaux).");
$faq[] = array("Comment puis-je marquer un sujet comme &quot;toujours lu&quot; ?", "Vous n'avez qu'a cliquer sur le bouton &agrave; c&ocirc;t&eacute;e du nom du sujet. Une fois cela fait, l'image du sujet devrait changer et sa position aussi.");
#$faq[] = array("I cannot mark sticky posts and announcements as 'permanent read'!", "Sticky posts and announcements are not allowed to be set as 'permanent read', as you might miss some very important information!");
$faq[] = array("Comment puis-je marquer une contribution, pour la retrouver plus facilement plus tard ?", "Sur chaque contribution, vous trouverez un bouton près du titre, que vous pouvez utiliser pour marquer cette contribution. Les contributions plus vieilles que " . (!empty($config['upi2db_auto_read']) ? $config['upi2db_auto_read'] : 0) . " jours or les contributions qui ont été écrites avant que vous ne vous inscriviez ne peuvent être marquées.");
$faq[] = array("Comment puis-je passer une contribution déjà lu en \"non lu\" à nouveau ?", "Sur chaque contribution, vous trouverez un bouton près du titre qui vous permettra de voir le message comme \"non lu\" à nouveau.");
$faq[] = array("Pourquoi ne puis-je pas marquer certaine contributions ?", "Les contributions marquées comme \"toujours lu\" dans un forum ou les contributions écrites avant que vous vous soyez inscrits ne peuvent être marquées. Cette règle s'applique aussi aux contributions vieilles de plus de " . (!empty($config['upi2db_auto_read']) ? $config['upi2db_auto_read'] : 0) . " jours.");
$faq[] = array("Est-ce que mes marquages sont permanents ?", "Non, tous les marquages faits sont automatiquement supprimés après " . (!empty($del_mark) ? $del_mark : 0) . " jours (depuis la création de la marque).");
$faq[] = array("Que signifie MAR?", "C'est un raccourci pour \"marquer comme lu(s)\"");


$faq[] = array("--", "phpBB 2");
$faq[] = array("Qui a écrit ce système de forum ?", 'phpBB2 (dans sa version basique, "vanilla") a été produit et copyrighté par le <a href="http://phpbb.com/" target="_blank">Groupe phpBB</a>. La license de distribution est GNU General Public License.');
$faq[] = array("Pourquoi telle fonctionnalité n'est pas disponible ?", "phpBB2 est un produit du Groupe phpBB. Si vous pensez qu'une fonctionnalité devrait être intégrée alors vous pouvez visiter le site phpbb.com et demander l'avis du Groupe phpBB.");
$faq[] = array("Quis puis-je contacter à propos des abus/des mentions légales sur ce forum ?", "Vous devez contacter l'administrateur du forum. Si vous ne pouvez pas le trouver ou ne pouvez le contacter, contactez en priorité les modérateurs pour leur demander à qui vous devez vous adresser. Si vous n'avez toujours aucune réponse, contactez le possesseur du domaine (whois) ou, si ce site est sur un hébergement gratuit (yahoo, free.fr, f2s.com, etc), contactez le département des abus de ce service. Veuillze noter que le Groupe phpBB n'a absolument aucun moyen de contrôle, et ne doit pas être contacté.");


$faq[] = array("--", "Qu&#39;est-ce que IcyPhoenix");
$faq[] = array("Qu'est-ce que IcyPhoenix ?", "IcyPhoenix est un CMS (Content Management System - système de gestion de contenu) qui permet de créer des sites avec beaucoup de fonctionnalités embarquées : forum, portail, pages customizables et blocks, téléchargements, galeries, et beaucoup d'autres choses.");
$faq[] = array("Qui a écrit IcyPhoenix ?", "IcyPhoenix est basé sur phpBB qui a comme license GNU General Public License, donc IcyPhoenix partage cette license. Cela signifie aussi qu'IcyPhoenix peut être librement modifié et distribué. La plupart des fichiers a été créé ou modifié par Mighty Gorgon et l'<a href=\"http://www.icyphoenix.com/\" target=\"_blank\">&Eacute;quipe IcyPhoenix</a>. Une liste non exhaustive des contributions est trouvable ici : <a href=\"http://www.icyphoenix.com/credits.php\" target=\"_blank\">Crédits IcyPhoenix</a>.");
$faq[] = array("Qui a fait la traduction fran&ccedil;aise d'IcyPhoenix ?", "
La traduction fran&ccedil; a &eacute;t&eacute; par Vendethiel et Yros");
?>